Repository redBorder/rb-arubacentral, pull requests merged in 2023-10, with the labels that each got.

#1 Refactored aruba service
  api/aruba_client.rb
  aruba.rb
  config.yml
  helpers/aruba_config.rb
  helpers/aruba_math.rb
  helpers/aruba_oauth.rb
  kafka/producer.rb
Labels: kind/feature, size/L

#2 support for multiple sensors, change config path and rename service
  aruba.rb
  config.yml
  helpers/aruba_config.rb
  rb_arubacentral.rb
Labels: kind/feature, size/L

#3 PR-3: Send AP status to rb_status
  .github/auto_assign.yml
  .github/workflows/pr.yml
  .github/workflows/rubocop.yml
  .gitignore
  .rubocop.yml
  api/aruba_client.rb
  config.yml
  helpers/aruba_config.rb
  helpers/aruba_math.rb
  helpers/aruba_oauth.rb
  kafka/producer.rb
  rb_arubacentral.rb
Labels: kind/feature, kind/bug, size/XL

#4 PR-4: Add unit tests
  .github/workflows/rubocop.yml
  .github/workflows/tests.yml
  Gemfile
  src/api/aruba_client.rb
  src/config.yml
  src/helpers/aruba_config.rb
  src/helpers/aruba_math.rb
  src/helpers/aruba_oauth.rb
  src/kafka/producer.rb
  src/rb_arubacentral.rb
  tests/all.sh
  tests/test_aruba_math.rb
  tests/test_aruba_oauth.rb
  tests/test_config.rb
  tests/test_event_generator.rb
  tests/test_kafka.rb
  tests/test_rest_client.rb
Labels: kind/feature, size/L

#6 PR-5: Add codecov coverage, change test suite, update readme
  .github/workflows/tests.yml
  Gemfile
  README.md
  Rakefile
  tests/all.sh
  tests/helpers/codecov_helper.rb
  tests/test_aruba_math.rb
  tests/test_aruba_oauth.rb
  tests/test_config.rb
  tests/test_event_generator.rb
  tests/test_kafka.rb
  tests/test_rest_client.rb
Labels: kind/documentation, size/M

#7 PR-7: update folder names
  lib/api/aruba_client.rb
  lib/config.yml
  lib/helpers/aruba_config.rb
  lib/helpers/aruba_math.rb
  lib/helpers/aruba_oauth.rb
  lib/kafka/producer.rb
  lib/rb_arubacentral.rb
  tests/test_aruba_math.rb
  tests/test_aruba_oauth.rb
  tests/test_config.rb
  tests/test_event_generator.rb
  tests/test_kafka.rb
  tests/test_rest_client.rb
Labels: kind/documentation, size/M

#8 PR-8: Add copyright text on each file
  lib/api/aruba_client.rb
  lib/helpers/aruba_config.rb
  lib/helpers/aruba_math.rb
  lib/helpers/aruba_oauth.rb
  lib/kafka/producer.rb
  lib/rb_arubacentral.rb
  tests/helpers/codecov_helper.rb
  tests/test_aruba_math.rb
  tests/test_aruba_oauth.rb
  tests/test_config.rb
  tests/test_event_generator.rb
  tests/test_kafka.rb
Labels: size/L, kind/documentation
