Repository redBorder/rb-arubacentral, pull requests merged in 2024-01, with the labels that each got.

#17 PR-17: Fix rubocop linter
  .rubocop.yml
  lib/api/aruba_client.rb
  lib/helpers/aruba_config.rb
  lib/helpers/aruba_logger.rb
  lib/helpers/aruba_oauth.rb
  lib/rb_arubacentral.rb
  test/test_aruba_logger.rb
  test/test_aruba_math.rb
  test/test_aruba_oauth.rb
  test/test_config.rb
  test/test_event_generator.rb
  test/test_kafka.rb
  test/test_rest_client.rb
Labels: enhancement, size/L

#18 PR-18: Task/#16061 enrich mac adress with sensor UUID
  lib/kafka/producer.rb
  lib/rb_arubacentral.rb
  test/test_event_generator.rb
Labels: kind/feature, size/S

#19 PR-19: create rpm package and check on valid arrays
  .github/workflows/rubocop.yml
  .gitignore
  Makefile
  lib/rb_arubacentral.rb
  packaging/rpm/Makefile
  packaging/rpm/rb-arubacentral.spec
  resources/systemd/rb-arubacentral.service
Labels: kind/feature, size/L
