Repository redBorder/rb-arubacentral, pull requests merged in 2024-02, with the labels that each got.

#20 PR-20: retrieve all client locations of more than 100
  lib/api/aruba_client.rb
Labels: kind/bug, size/M

#21 PR-21: Add cache system
  .github/workflows/rubocop.yml
  .rubocop.yml
  README.md
  assets/cache.png
  assets/workflow.png
  lib/api/aruba_client.rb
  lib/config.yml
  lib/helpers/aruba_cache.rb
  lib/rb_arubacentral.rb
  test/test_aruba_cache.rb
  test/test_rest_client.rb
Labels: kind/feature, size/L

#23 PR-23: BugFix - The associated clients got associated with turned-off access points.
  lib/api/aruba_client.rb
Labels: kind/bug, size/XS

#22 PR-22: Add sensor_uuid and sensor_name to enrich
  lib/kafka/producer.rb
  lib/rb_arubacentral.rb
  test/test_event_generator.rb
Labels: kind/feature, size/S

#24 PR-24: The associated clients got associated with turned-off access
  lib/api/aruba_client.rb
  lib/rb_arubacentral.rb
Labels: kind/bug, size/S
