Repository redBorder/rb-arubacentral, pull requests merged in 2024-04, with the labels that each got.

#27 PR-027: update specfile according to new version changes
  packaging/rpm/rb-arubacentral.spec
Labels: kind/bug, size/S

#28 PR-28: Fix floor location and add rpm workflow
  .github/workflows/rpm.yml
  VERSION
  bin/api/aruba_client.rb
  bin/helpers/aruba_auth.rb
  bin/helpers/aruba_data_post_processor.rb
Labels: size/L, kind/bug

#29 PR-29: Release 0.0.3
  .github/workflows/rpm.yml
  VERSION
  bin/api/aruba_client.rb
  bin/helpers/aruba_auth.rb
  bin/helpers/aruba_data_post_processor.rb
Labels: size/L, kind/bug

#30 PR-30: Update VERSION
  VERSION
Labels: kind/documentation, size/XS

#31 PR-31: Release 0.0.4
  .rubocop.yml
  VERSION
  bin/api/aruba_client.rb
Labels: kind/bug, size/S

#32 Check ap is not nil before using it
  bin/api/aruba_client.rb
Labels: kind/bug, size/S

#33 Release 0.0.5
  VERSION
  bin/api/aruba_client.rb
Labels: kind/documentation, size/S
